; "Codewords for Heart of Ice"

<OBJECT CODEWORD-DIAMOND
    (DESC "Diamond")
    (SYNONYM DIAMOND)>

<OBJECT CODEWORD-ENKIDU
    (DESC "Enkidu")
    (SYNONYM ENKIDU)>

<OBJECT CODEWORD-HUMBABA
    (DESC "Humbaba")
    (SYNONYM HUMBABA)>

<OBJECT CODEWORD-MALLET
    (DESC "Mallet")
    (SYNONYM MALLET)>
