<CONSTANT SKILL-GLOSSARY <LTABLE NONE>>
<CONSTANT CHARACTERS <LTABLE NONE>>

<OBJECT CHARACTER-CUSTOM
    (DESC "Custom Character")
    (SYNONYM CHARACTER)
    (ADJECTIVE CUSTOM)
    (LDESC "Custom character with user selected skills")
    (LIFE-POINTS 10)
    (MONEY 10)
    (FLAGS PERSONBIT NARTICLEBIT)>
