<OBJECT VEHICLE
    (DESC "Manta sky-car")
    (SYNONYM CAR)
    (ADJECTIVE MANTA SKY)
    (FLAGS VEHICLEBIT)>

<OBJECT VEHICLES
    (DESC "Manta sky-cars")
    (SYNONYM CARS)
    (ADJECTIVE MANTA SKY)
    (FLAGS CONTBIT OPENBIT)>
